# Generated by Django 6.0.6 on 2026-08-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('alley', models.CharField(blank=True, max_length=100, null=True)),
                ('plate', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
