# Generated by Django 6.0.6 on 2026-08-31 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cart', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='Cart.cart')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='Product.product')),
            ],
        ),
    ]
