# Generated by Django 6.0.6 on 2026-09-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartItem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Cart',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='Product',
            new_name='product',
        ),
    ]
