# Generated by Django 6.0.6 on 2026-08-31 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OP', 'Order_Placed'), ('OC', 'Order_Confirmed'), ('OP', 'Order_Processing'), ('IT', 'In_Transit'), ('OFD', 'Out_for_Delivery'), ('D', 'Delivered'), ('OFD', 'Out_for_Delivery')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='Address.address')),
            ],
        ),
    ]
